import os
import logging
from datetime import datetime
from sqlalchemy import create_engine, Column, Integer, Float, String, DateTime, Boolean, Text
from sqlalchemy.orm import DeclarativeBase, Session

logger = logging.getLogger(__name__)

DB_PATH = "trades.db"


class Base(DeclarativeBase):
    pass


class Trade(Base):
    """Every paper and live trade entry and exit."""
    __tablename__ = "trades"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    symbol           = Column(String(20), nullable=False)
    direction        = Column(String(4), nullable=False)   # BUY / SELL
    quantity         = Column(Integer, nullable=False)
    entry_price      = Column(Float)
    exit_price       = Column(Float)
    entry_time       = Column(DateTime, default=datetime.now)
    exit_time        = Column(DateTime)
    pnl              = Column(Float, default=0.0)
    exit_reason      = Column(String(50))                  # SL / TARGET / TRAIL / KILL_SWITCH
    strategy_name    = Column(String(50))
    sentiment_score  = Column(Float)
    sector           = Column(String(50))
    order_id         = Column(String(50))
    is_paper         = Column(Boolean, default=True)
    status           = Column(String(20), default="OPEN")  # OPEN / CLOSED


class Signal(Base):
    """Every signal generated by strategies — including blocked ones."""
    __tablename__ = "signals"

    id               = Column(Integer, primary_key=True, autoincrement=True)
    symbol           = Column(String(20), nullable=False)
    direction        = Column(String(4), nullable=False)
    strategy_name    = Column(String(50))
    sentiment_score  = Column(Float)
    ltp              = Column(Float)
    timestamp        = Column(DateTime, default=datetime.now)
    status           = Column(String(20))                  # APPROVED / BLOCKED
    block_reason     = Column(String(100))


class SystemLog(Base):
    """System-level events: engine start, stop, errors, kill switch."""
    __tablename__ = "system_log"

    id        = Column(Integer, primary_key=True, autoincrement=True)
    timestamp = Column(DateTime, default=datetime.now)
    level     = Column(String(10))                         # INFO / WARNING / ERROR
    event     = Column(String(100))
    detail    = Column(Text)


class TradeDB:
    """SQLite ORM wrapper. All DB operations go through this class."""

    def __init__(self, db_path: str = DB_PATH):
        self.db_path = db_path
        self.engine  = create_engine(f"sqlite:///{db_path}", echo=False)
        Base.metadata.create_all(self.engine)
        logger.info(f"TradeDB initialised → {db_path}")

    def log_signal(self, symbol: str, direction: str, strategy: str,
                   sentiment: float, ltp: float,
                   status: str, block_reason: str = "") -> int:
        with Session(self.engine) as session:
            sig = Signal(
                symbol=symbol, direction=direction,
                strategy_name=strategy, sentiment_score=sentiment,
                ltp=ltp, status=status, block_reason=block_reason
            )
            session.add(sig)
            session.commit()
            return sig.id

    def open_trade(self, symbol: str, direction: str, quantity: int,
                   entry_price: float, strategy: str, sentiment: float,
                   sector: str, order_id: str, is_paper: bool = True) -> int:
        with Session(self.engine) as session:
            trade = Trade(
                symbol=symbol, direction=direction,
                quantity=quantity, entry_price=entry_price,
                strategy_name=strategy, sentiment_score=sentiment,
                sector=sector, order_id=order_id, is_paper=is_paper,
                status="OPEN"
            )
            session.add(trade)
            session.commit()
            return trade.id

    def close_trade(self, trade_id: int, exit_price: float,
                    exit_reason: str) -> float:
        with Session(self.engine) as session:
            trade = session.get(Trade, trade_id)
            if not trade:
                logger.error(f"Trade ID {trade_id} not found")
                return 0.0
            trade.exit_price  = exit_price
            trade.exit_time   = datetime.now()
            trade.exit_reason = exit_reason
            trade.status      = "CLOSED"
            if trade.direction == "BUY":
                trade.pnl = (exit_price - trade.entry_price) * trade.quantity
            else:
                trade.pnl = (trade.entry_price - exit_price) * trade.quantity
            session.commit()
            return trade.pnl

    def get_open_trades(self) -> list:
        with Session(self.engine) as session:
            return session.query(Trade).filter_by(status="OPEN").all()

    def get_daily_pnl(self) -> float:
        with Session(self.engine) as session:
            trades = session.query(Trade).filter(
                Trade.entry_time >= datetime.now().replace(
                    hour=0, minute=0, second=0)
            ).all()
            return sum(t.pnl or 0.0 for t in trades)

    def log_system(self, level: str, event: str, detail: str = ""):
        with Session(self.engine) as session:
            session.add(SystemLog(level=level, event=event, detail=detail))
            session.commit()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s — %(message)s")

    # Use test DB so we don't pollute the real one
    db = TradeDB(db_path="test_trades.db")

    # Test: open a trade
    trade_id = db.open_trade(
        symbol="INFY", direction="BUY", quantity=100,
        entry_price=1842.50, strategy="MorningBreakout",
        sentiment=-0.963, sector="NIFTY IT",
        order_id="PAPER_001", is_paper=True
    )
    print(f"✅ Trade opened  — ID: {trade_id}")

    # Test: log a signal
    sig_id = db.log_signal(
        symbol="INFY", direction="BUY",
        strategy="MorningBreakout", sentiment=-0.963,
        ltp=1842.50, status="APPROVED"
    )
    print(f"✅ Signal logged — ID: {sig_id}")

    # Test: close the trade
    pnl = db.close_trade(trade_id, exit_price=1870.0, exit_reason="TARGET")
    print(f"✅ Trade closed  — P&L: ₹{pnl:.2f}")

    # Test: daily P&L
    daily = db.get_daily_pnl()
    print(f"✅ Daily P&L     — ₹{daily:.2f}")

    # Test: system log
    db.log_system("INFO", "ENGINE_START", "Morning Beetle engine started")
    print(f"✅ System log    — entry written")

    # Test: query back
    print(f"\n── Query Test ──")
    open_trades = db.get_open_trades()
    print(f"  Open trades: {len(open_trades)}")

    # Cleanup test DB
    import os
    db.engine.dispose()  # Release SQLite file lock
    os.remove("test_trades.db")
    print(f"\n✅ TradeDB all tests passed. test_trades.db cleaned up.")